config/routes.rb
Rails.application.routes.draw do
  resources :teas
  root "teas#index"

  resources :purchases

  post "payment-intent", to: "purchases#intent"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :tea
  enum status: { pending: 0, approved: 1, unapproved: 2 }
end

app/models/tea.rb
class Tea < ApplicationRecord
  has_many :purchases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_stripe_key


  private

    def set_stripe_key
      Stripe.api_key = Rails.application.credentials.dig(:stripe, :secret_key)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  # before_action :set_tea
  def new
    @purchase = Purchase.new
    @tea = Tea.find_by(name: params[:name])
  end

  def create

    @purchase = Purchase.new(purchase_params)

    @tea = Tea.find(params[:purchase][:tea_id])

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to root_url, notice: "Tea was successfully purchased!"}
      else
        format.html { redirect_to new_purchase_path(params: {name: tea.name}), status: :unprocessable_entity}
      end
    end
  end
  def intent
    @tea = Tea.find(params[:_json])
    amount = @tea.price * 100

    payment_intent= Stripe::PaymentIntent.create(
      amount: amount, 
      currency: 'usd', 
      automatic_payment_methods: {
        enabled: true
      },
      metadata: {
        tea_id: @tea.id
      }
    )

    respond_to do |format|
      format.json { render json: { clientSecret: payment_intent['client_secret']}}
    end
  end

  private
    def set_tea
      @tea = Tea.find(params[:id])
    end
    def purchase_params
      params.require(:purchase).permit(:status, :name, :email, :customer_paid, :tea_id )
    end
end

app/controllers/teas_controller.rb
class TeasController < ApplicationController
  before_action :set_tea, only: %i[ show edit update destroy ]

  # GET /teas or /teas.json
  def index
    if params[:query].present?
      @teas = Tea.where("name iLIKE ?", "#{params[:query]}%")
    else
      @teas = Tea.all
    end


    if turbo_frame_request?
      #move to application helper
      render partial: "teas", locals: { teas: @teas }
    else
      render :index
    end
  end

  # GET /teas/1 or /teas/1.json
  def show
  end

  # GET /teas/new
  def new
    @tea = Tea.new
  end

  # GET /teas/1/edit
  def edit
  end

  # POST /teas or /teas.json
  def create
    @tea = Tea.new(tea_params)

    respond_to do |format|
      if @tea.save
        format.html { redirect_to tea_url(@tea), notice: "Tea was successfully created." }
        format.json { render :show, status: :created, location: @tea }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tea.errors, status: :unprocessable_entity }
      end
    end
  end

  def intent
    
  end

  # PATCH/PUT /teas/1 or /teas/1.json
  def update
    respond_to do |format|
      if @tea.update(tea_params)
        format.html { redirect_to tea_url(@tea), notice: "Tea was successfully updated." }
        format.json { render :show, status: :ok, location: @tea }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teas/1 or /teas/1.json
  def destroy
    @tea.destroy

    respond_to do |format|
      format.html { redirect_to teas_url, notice: "Tea was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tea
      @tea = Tea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tea_params
      params.require(:tea).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teas_helper.rb
module TeasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeaSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="stripe-public-key" content="<%=Rails.application.credentials.dig(:stripe, :public_key) %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "https://js.stripe.com/v3/", 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container mx-auto my-16 lg:px-10 px-4">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/copy_purchase_form.html.erb
<%= form_with(model: @tea, data: { turbo: false, action: "submit->payment#purchase", payment_target: "form"}) do |form| %>
  <% if tea.errors.any? %>
    <div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
      <h2 class="text-lg font-semibold mb-3"><%= pluralize(tea.errors.count, "error") %> prohibited this tea from being saved:</h2>

      <ul class="list-disc leading-relaxed">
        <% tea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="font-bold text-lg mb-3 mt-6">Personal details</h3>

  <div class="grid grid-col-1 lg:grid-cols-2 gap-6 mb-10">
    <div>
      <%= form.label :name, class: label_class %>
      <%= form.text_field :name, class: input_class, data: { payment_target: "name" } %>
    </div>

    <div>
      <%= form.label :email, class: label_class %>
      <%= form.text_field :email, class: input_class, data: { payment_target: "email" } %>
    </div>
  </div>

  <div class="mb-6">
    <%= form.label :notes, class: label_class %>
    <%= form.rich_text_area :notes, class: input_class %>
  </div>

  <h3 class="font-bold text-lg mb-3">Tea details</h3>

<% end %>

app/views/purchases/_purchase_form.html.erb
<%=form_with(model: purchase, data: { turbo: false, action: "submit->payment#purchase", payment_target: "form"} ) do |form| %>
  <h3 class="font-bold text-lg mb-3 mt-6">Personal Details</h3>
  <div class="grid grid-col-1 lg:grid-cols-2 gap-6 mb-10">
    <div class="mb-6">
      <%= form.label :name%>
      <%= form.text_field :name,  data: { payment_target: "name" } %>
    </div>

    <div>
      <%= form.label :email %>
      <%= form.text_field :email,  data: { payment_target: "email" } %>
    </div>

    <div>
      <%= form.hidden_field :tea_id, value: @tea.id %>
    </div>
  </div>
  <%= form.submit "Buy #{@tea.name} Tea", class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium", data: { payment_target: "submit"} %>
<%end%>


</div>
<%= link_to 'Back to teas', teas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

app/views/purchases/new.html.erb
<h1 class="font-bold text-3xl mb-6"> Purchase <%=@tea.name%> Tea for <%=number_to_currency(@tea.price)%></h1>
<div class="max-w-3xl mx-auto px-4">
  <div data-controller="payment" data-payment-item-value="<%=@tea.id%>" data-payment-return-url-value="<%=root_url%>">
    <div clas="mb-10">
      <h3 class="font-bold text-xl mb-3">Enter payment details</h3>
      <div id="payment-element" data-payment-target="element"></div>
      <div data-payment-target="message" class="hidden"></div>
    </div>
    <%= render 'purchase_form', purchase: @purchase %>
  </div>
</div>

app/views/teas/_form.html.erb
<%= form_with(model: tea, class: "contents") do |form| %>
  <% if tea.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(tea.errors.count, "error") %> prohibited this tea from being saved:</h2>

      <ul>
        <% tea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/teas/_tea.html.erb
<div id="<%= dom_id tea %>">
  <p class="text-lg leading-loose">
    <%= link_to tea.name, new_purchase_path(params: {name: tea.name}), class: "text-orange-600 underline hover:text-orange-700" %>
  </p>
</div>

app/views/teas/_teas.html.erb
<%= turbo_frame_tag "teas" do %>
  <%= render teas %>
<% end %>

app/views/teas/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing tea</h1>

  <%= render "form", tea: @tea %>

  <%= link_to "Show this tea", @tea, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to teas", teas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/teas/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="font-bold text-3xl mb-3">Teas</h1>
<%= form_with(url: teas_path, method: :get, data: {controller: "search-form",turbo_frame: "teas", turbo_action: "advance"}) do |form| %>

  <%= form.label :query, "Search by tea name:", class: "block mb-2" %>
  <div class="flex space-x-3">
    <%= form.text_field :query, class: "py-3 px-4 rounded border ring-0 focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none", data: { action: "input->search-form#search"} %>

    <%= form.submit 'Search', class: "px-4 py-3 font-medium
  bg-orange-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100" %>
  </div>
<% end %>

<div class="my-16">
  <%= render @teas %>
</div>


<%= link_to "New Tea", new_tea_path, class: "px-4 py-3 font-medium
  bg-orange-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100"%>

app/views/teas/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New tea</h1>

  <%= render "form", tea: @tea %>

  <%= link_to 'Back to teas', teas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/teas/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <p><%= @tea.name %>,  $<%=@tea.price%></p>

    <%= link_to 'Buy this tea', '#', class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this tea', edit_tea_path(@tea), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this tea', tea_path(@tea), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to teas', teas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>
<div>

<div data-controller="payment" data-payment-item-value="<%=@tea.id%>" data-payment-return-url-value="<%=root_url%>">
  <div class="mb-6">
    <h3 class="font-bold text-3xl mb-6">Enter Payment Details</h3>
    <div id="payment-element" data-payment-target="element"></div>
    <div data-payment-target="message" class="hidden"></div>
  </div>

</div>